<?php

namespace Tvup\LaravelFejlVarp\Http\Requests;

use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;

class ApiRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    public function failedValidation(Validator $validator)
    {
        throw new \Exception(strval(trans($validator->errors()->first())));
    }

    protected function failedAuthorization()
    {
        parent::failedAuthorization(); // TODO: Change the autogenerated stub
    }
}
