name: PHPStan

on: [push]

permissions:
  contents: write

jobs:
  phpstan:
    name: phpstan
    runs-on: ubuntu-latest

    env:
      phpversion: '8.3'

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.phpversion }}
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@v1

      - name: Run PHPStan
        run: ./vendor/bin/phpstan --error-format=github
