name: run-tests

on:
  push:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]
        php-laravel-testbench:
          - {php: 8.0.2, laravel: 9.*, testbench: 7.*}
          - {php: 8.1, laravel: 9.*, testbench: 7.*}
          - {php: 8.2, laravel: 9.*, testbench: 7.*}
          - {php: 8.3, laravel: 9.*, testbench: 7.*}
          - {php: 8.1, laravel: 10.*, testbench: 8.*}
          - {php: 8.2, laravel: 10.*, testbench: 8.*}
          - {php: 8.3, laravel: 10.*, testbench: 8.*}
          - {php: 8.2, laravel: 11.*, testbench: 9.*}
          - {php: 8.3, laravel: 11.*, testbench: 9.*}

    name: PHP ${{ matrix.php-laravel-testbench.php }} - Laravel ${{ matrix.php-laravel-testbench.laravel }} - Testbench ${{ matrix.php-laravel-testbench.testbench }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-laravel-testbench.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.php-laravel-testbench.laravel }}"
          composer require "orchestra/testbench:${{ matrix.php-laravel-testbench.testbench }}" --dev
          composer update --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/pest
