name: run-tests

on:
  push:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          # Laravel 9, PHP 8.0.2 and above, Testbench 7.*
          - php: 8.0.2
            laravel: 9.*
            testbench: 7.*
          - php: 8.1
            laravel: 9.*
            testbench: 7.*
          - php: 8.2
            laravel: 9.*
            testbench: 7.*
          - php: 8.3
            laravel: 9.*
            testbench: 7.*
          # Laravel 10, PHP 8.1 and above, Testbench 8.*
          - php: 8.1
            laravel: 10.*
            testbench: 8.*
          - php: 8.2
            laravel: 10.*
            testbench: 8.*
          - php: 8.3
            laravel: 10.*
            testbench: 8.*
          # Laravel 11, PHP 8.2 and above, Testbench 9.*
          - php: 8.2
            laravel: 11.*
            testbench: 9.*
          - php: 8.3
            laravel: 11.*
            testbench: 9.*

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }} - Testbench ${{ matrix.testbench }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-update
          composer require "orchestra/testbench:${{ matrix.testbench }}" --dev --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/pest
